// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/BIC-Final-Project/backend/configs/env"
	"github.com/BIC-Final-Project/backend/internal/operational/http/handler"
	"github.com/BIC-Final-Project/backend/internal/operational/repository"
	"github.com/BIC-Final-Project/backend/internal/operational/usecase"
	"github.com/BIC-Final-Project/backend/internal/storage"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitFasilitas(db *mongo.Database, env2 env.EnvVars) *handler.FasilitasHandler {
	fasilitasRepository := repository.NewFasilitasRepository(db)
	s3Service := storage.NewS3Service(env2)
	fasilitasUsecase := usecase.NewFasilitasUsecase(fasilitasRepository, s3Service)
	fasilitasHandler := handler.NewFasilitasHandler(fasilitasUsecase)
	return fasilitasHandler
}

func InitMembershipType(db *mongo.Database) *handler.MembershipTypeHandler {
	membershipTypeRepository := repository.NewMembershipTypeRepository(db)
	membershipTypeUsecase := usecase.NewMembershipTypeUsecase(membershipTypeRepository)
	membershipTypeHandler := handler.NewMembershipTypeHandler(membershipTypeUsecase)
	return membershipTypeHandler
}
